spring:
  application:
        name: match-engine
  cloud:
      consul:
        host: ${CONSUL_HOST}
        port: ${CONSUL_PORT}
        discovery:
          tags: cj-engine=1.0
          ip-address: ${DOCKER_IP}
          port: ${SERVER_PORT}
          prefer-ip-address: true
          health-check-path: /health
          deregister: true
          instance-id: ${spring.application.name}-${DOCKER_IP}:${SERVER_PORT}

  datasource:
      name: mydb
      url: jdbc:mysql://${MYSQL_HOST}/cj_mengine?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
      username: ${MYSQL_USER}
      password: ${MYSQL_PWD}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      spring.datasource.filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
#      cluster:
#        nodes: 172.28.2.89:6379
#        max-redirects: 6
      pool:
        max-idle: 100
        min-idle: 5
        max-wait: -1
        max-active: 100
      password: ${REDIS_PWD}
      so-timeout: 6000
      timeout: 6000
      max-attempts: 6
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

endpoints:
  enabled: false
  metrics:
    enabled: true
    sensitive: false
    path: /ep/metrics
  info:
    enabled: true
    sensitive: false
    path: /ep/info
  heapdump:
    enabled: true
    sensitive: false
    path: /ep/heapdump
  trace:
    enabled: true
    sensitive: false
    path: /ep/trace
  health:
    enabled: true
    sensitive: false

server:
  port: ${SERVER_PORT}
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8